---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    env: prd
spec:
  replicas: 10
  template:
    spec:
      containers:
      - image: nginx:1.20.0
        name: nginx
        resources:
          limits:
            memory: 10Gi
        env:
        - name: HELLO
          value: world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    env: prd
    component: backend
spec:
  replicas: 20
  template:
    spec:
      containers:
      - image: nginx:1.20.0
        name: nginx
        resources:
          limits:
            memory: 20Gi
