apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: caruccio/app:1.0.2 # {"$imagepolicy": "flux-system:app"}
        name: nginx
        resources: {}
        env:
        - name: HELLO
          value: world
        - name: IMAGE_NAME
          value: "caruccio/app" # {"$imagepolicy": "flux-system:app:name"}
        - name: IMAGE_TAG
          value: "1.0.2" # {"$imagepolicy": "flux-system:app:tag"}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: nginx
  namespace: default
spec:
  rules:
  - host: kind.io
    http:
      paths:
      - backend:
          service:
            name: app
            port:
              number: 80
        path: /
        pathType: Prefix
