apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: app
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'Flux Autocommit: {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: /images/app
    strategy: Setters

