apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/caruccio/flux-intro/main/helm/chart/repo/
