apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app
      sourceRef:
        kind: HelmRepository
        name: app
      version: 0.2.1
  interval: 1m0s
  targetNamespace: app
  install:
    createNamespace: true
  upgrade:
    timeout: 30s
    remediation:
      retries: 3
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: false


