---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        env:
        - name: EXIT_CODE
          value: 0
        command:
        - /bin/sh
        - -c
        - |-
          if [ $EXIT_CODE != 0 ]; then
            sleep 2
            exit $EXIT_CODE
          fi
          exec nginx" -g "daemon off"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        env:
        - name: EXIT_CODE
          value: 0
        command:
        - /bin/sh
        - -c
        - |-
          if [ $EXIT_CODE != 0 ]; then
            sleep 2
            exit $EXIT_CODE
          fi
          exec nginx" -g "daemon off"
